name: INTSUM CI

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: |
          cd build
          make VERBOSE=1
      - name: Test
        run: |
          cd build
          ctest --output-on-failure
      - name: Pack
        run: |
          cd build
          cpack -G DEB
      - name: Save package
        uses: actions/upload-artifact@v2
        with:
          name: build_linux_package
          path: build/*.deb

  test_linux:
    runs-on: ubuntu-20.04
    needs: [build_linux]
    steps:
      - uses: actions/checkout@v2
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: build_linux_package
      - name: Install package
        run: sudo apt install -y ./intsum*Linux.deb
      - name: Run test
        run: bash .github/scripts/test.sh

  release:
    runs-on: ubuntu-20.04
    needs: [build_linux, test_linux]
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - name: Download package for Linux
        uses: actions/download-artifact@v2
        with:
          name: build_linux_package
      - uses: softprops/action-gh-release@v1
        with:
          files: "*.deb"
