name: INTSUM CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: |
          cd build
          make VERBOSE=1
