name: INTSUM CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: |
          cd build
          make VERBOSE=1
      - name: Test
        run: |
          cd build
          ctest --output-on-failure
      - name: Pack
        run: |
          cd build
          cpack -G DEB
      - name: Save package
        uses: actions/upload-artifact@v2
        with:
          name: build_linux
          path: build/*.deb
